[package]
name = "sppuffin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description.workspace = true

[dependencies]
jni = { version = "0.22.4", features = ["invocation"] }
jni-macros = "0.22.4"
javac = "0.1.2"
comparable = { workspace = true, features = ["derive"] }
puffin = { path = "../puffin" }
puffin-build = { path = "../puffin-build" }
extractable-macro = { path = "../extractable-macro" }
serde = { version = "1.0.228", features = ["derive"] }
log = "0.4.29"
once_cell = { workspace = true }
rand = "0.8"
