
name: setup
description: Setup toolchains and tools

inputs:
  key:
    description: 'Additional key for caching'
    required: false

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install toolchain
      shell: bash
      run: just default-toolchain
    - uses: Swatinem/rust-cache@v1
      with:
        sharedKey: ${{ inputs.key }}
    - name: Setup LLVM search path
      shell: bash
      run: |
        echo "LD_LIBRARY_PATH=$(dirname $(clang -print-file-name=libclang_rt.asan-x86_64.so))" >> $GITHUB_ENV
