
name: setup
description: Setup toolchains and tools

inputs:
  key:
    description: 'Additional key for caching'
    required: false
  save-cache:
    description: 'If the cache is saved'
    default: "true"
    required: false

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install toolchain
      shell: bash
      run: just default-toolchain
    - name: Remove dotnet to have more disk space available
      shell: bash
      run: sudo rm -rf /usr/share/dotnet
    - uses: Swatinem/rust-cache@v2
      with:
        sharedKey: ${{ inputs.key }}
        save-if: ${{ inputs.save-cache }}
