
name: setup
description: Setup toolchains and tools

inputs:
  key:
    description: 'Additional key for caching'
    required: false

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install toolchain
      shell: bash
      run: just default-toolchain
    - uses: Swatinem/rust-cache@v1
      with:
        sharedKey: ${{ inputs.key }}
