name: setup
description: Setup toolchains and tools

inputs:
  key:
    description: 'Additional key for caching'
    required: false
  save-cache:
    description: 'If the cache is saved'
    default: "true"
    required: false

runs:
  using: "composite"
  steps:
    - name: setup CI env
      shell: bash
      run: |
        #!/usr/bin/env bash
        export_env() {
          local var=${1}
          local val=${2:-${!1}}

          printf '%s=%s\n' "${var}" "${val}" >> "${GITHUB_ENV}"
        }

        export_env RUST_LOG "info"
        export_env CLANG_PATH "$(clang -print-prog-name=clang)"
        export_env LIBCLANG_PATH "$(llvm-config-"$(clang -dumpversion | cut -d '.' -f1)" --libdir)"
        export_env BINDGEN_EXTRA_CLANG_ARGS "-v"

    - uses: extractions/setup-just@v2
    - name: Install toolchain
      shell: bash
      run: just default-toolchain
    - name: Remove dotnet to have more disk space available
      shell: bash
      run: sudo rm -rf /usr/share/dotnet
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.key }}
        save-if: ${{ inputs.save-cache }}
