#!/bin/env python
import argparse
from tlspuffin_analyzer import *


def main():
    parser = argparse.ArgumentParser(description='Plots statistics')
    parser.add_argument('experiment', type=str,
                        help='Name of the experiment')
    parser.add_argument('--ssh',
                        action='store_true',
                        help='Enable SSH mode')
    args = parser.parse_args()

    if not args.ssh:
        stats_path = "%s/stats.json" % args.experiment
        all_stats = load_json_slurpy(stats_path)
    else:
        all_stats = load_json_slurpy_ssh("pesto-calc.loria.fr", "/local-homes/mammann/tlspuffin", args.experiment)

    start_date = get_start_date(all_stats)
    keys = get_keys(all_stats)
    print("Available keys: %s" % keys)

    for group in group_by_id(all_stats):
        plot_client_stats(start_date, group)

    plt.show()


main()
