[package]
name = "sshpuffin"
description = "SSH protocol implementation for fuzzing with tlspuffin"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["sancov"]
# Current put supports claims
claims = []

# Sanitizer / instrumentation flags forwarded to the C harness build
asan    = ["puffin/asan"]
sancov  = ["puffin/sancov"]
gcov    = []
llvm_cov = []

[dependencies]
puffin       = { path = "../puffin" }
puffin-build = { path = "../puffin-build" }
extractable-macro = { path = "../extractable-macro" }
log          = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
comparable   = { workspace = true, features = ["derive"] }
libc         = { workspace = true }
once_cell    = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
test-log   = { workspace = true }

[build-dependencies]
puffin-build = { path = "../puffin-build" }
bindgen      = { workspace = true }

