use proc_macro2::TokenStream;
use quote::{format_ident, quote, ToTokens};
use syn::Token;

/// Mandatory attribute naming the signature the generated functions are registered into:
/// `#[constructor(SIGNATURE, ProtocolTypes)]`.
const CONSTRUCTOR_ATTR: &str = "constructor";

/// Helper attribute marking a field that is *not* a constructor parameter and is instead
/// initialised from the expression it wraps: `#[constructor_default(EXPR)]`.
const DEFAULT_ATTR: &str = "constructor_default";

/// Opt-in attribute marking a list *element* type: `#[constructor_list]`.
///
/// It emits `impl VecCodecWoSize for Self`, which is what gives `Vec<Self>` a `Codec` — and hence
/// makes it an `EvaluatedTerm` a `DYTerm::List` can build — and registers `Vec<Self>` as a
/// readable type alongside `Self`.
///
/// It does **not** register the list type: that follows from the constructor arguments taking a
/// `Vec<..>`, wherever they are, so a `Vec<Self>` no symbol takes is no list type of the
/// signature.
///
/// `impl VecCodecWoSize` needs `Self: Codec` (not merely `CodecP`) and says the elements are
/// encoded back to back, with no length prefix of their own. That only holds for genuine list
/// element types, so it is off by default and must be requested explicitly.
///
/// One flag is accepted, `#[constructor_list(no_codec_impl)]`:
///
/// * `no_codec_impl` — do not emit `impl VecCodecWoSize for Self`. Required when the type already
///   has one; the impl is only a convenience for types that do not.
///
/// It composes with [`SKIP_ALL_ATTR`], which drops the constructors while keeping the codec impl
/// and the readable `Vec<Self>`. That replaces an earlier `only` flag, which was all-or-nothing:
/// pairing with the skip attribute means a few variants can be kept via [`NO_SKIP_ATTR`].
const LIST_ATTR: &str = "constructor_list";

/// Opt-out attribute excluding an enum variant entirely: `#[constructor_skip]`, on the variant.
///
/// The variant's constructor is not generated. Use it for variants whose payload type no other
/// function symbol can produce — registering them would only add a symbol the term algebra can
/// never build an argument for — or whose value the rest of the crate cannot act on (an
/// unimplemented cipher suite or key-exchange group).
///
/// It takes no argument. A type-level `#[constructor_skip(Variant, ...)]` naming variants used to
/// be accepted for enums generated by a macro that could not annotate them individually; it is
/// rejected now that `enum_builder!` forwards per-variant attributes, because matching variants by
/// name silently skipped nothing when a name was misspelled or a variant later renamed.
///
/// For a wide enum where only a handful of variants are wanted, invert the polarity with
/// [`SKIP_ALL_ATTR`] instead of annotating every variant.
const SKIP_ATTR: &str = "constructor_skip";

/// Type-level attribute inverting the polarity of [`SKIP_ATTR`]: `#[constructor_skip_all]`.
///
/// Every variant is skipped unless it opts back in with [`NO_SKIP_ATTR`]. Use it when the wanted
/// variants are the exception rather than the rule — a protocol enum listing every IANA-registered
/// value, of which the crate implements a handful (`CipherSuite`, ...), where the opt-out form
/// would mean annotating hundreds of variants and silently regaining a symbol each time the list
/// grows upstream.
///
/// It takes no argument. On a **struct**, which has no variants to opt back in, it drops the single
/// constructor outright.
///
/// It composes with [`LIST_ATTR`]: the `Vec<Self>` constructors are about the list, not the
/// variants, so it still happens. That pairing — the codec impl plus a curated handful of
/// values — is what a wide protocol enum wants, and it replaces the earlier
/// `#[constructor_list(only)]` flag, which could not keep any variant.
const SKIP_ALL_ATTR: &str = "constructor_skip_all";

/// Opt-in attribute keeping one variant under [`SKIP_ALL_ATTR`]: `#[constructor_no_skip]`, on the
/// variant.
///
/// It takes no argument, and is rejected on a type that does not carry [`SKIP_ALL_ATTR`], where it
/// would be a no-op — variants are generated by default there.
const NO_SKIP_ATTR: &str = "constructor_no_skip";

/// Opt-out attribute excluding the type from the signature's readable types:
/// `#[constructor_no_try_read]`, on the type.
///
/// By default the derive registers the type with `puffin::define_readable_types!`, so that
/// `try_read_bytes` can turn a bitstring back into a value of it — the counterpart of the `Codec`
/// encoding the term algebra produces. Add this attribute when reading the type back is not
/// meaningful:
///
/// * the type has no `Codec` at all (only `CodecP`, e.g. a dummy codec), in which case leaving it
///   out is *required* — the registration would not compile;
/// * its `read` needs context the bitstring does not carry, so it always fails (a payload keyed by
///   a content or handshake type stored in the enclosing message);
/// * its `encode` and `read` do not round-trip, e.g. `read` skips fields the enclosing message
///   owns, or `encode` writes a tag that the enclosing type's `read` consumes. Reading such a
///   bitstring back silently yields a different value, which is worse than failing.
///
/// It takes no argument. It also suppresses the `Vec<Self>` registration that
/// [`LIST_ATTR`] would otherwise add.
const NO_TRY_READ_ATTR: &str = "constructor_no_try_read";

/// Derives free constructor functions for a type and registers them into a puffin signature,
/// turning each struct / enum variant into a function symbol usable by the term algebra.
///
/// The type itself is registered as one of the signature's *readable types*, so that
/// `try_read_bytes` can read a bitstring back into it — see `#[constructor_no_try_read]` under
/// [Helper attributes](#helper-attributes) for when and how to opt out.
///
/// # Generated constructors
///
/// * For a **struct** `Foo`: one `fn_foo(&Field, ...) -> Result<Foo, FnError>` (no-arg for a unit
///   struct).
/// * For an **enum** `Foo`: one `fn_foo_<variant>(...) -> Result<Foo, FnError>` per variant.
///
/// Names are fully lower-cased (`HTTPResponse` → `fn_httpresponse`). Every field becomes a
/// by-reference parameter (`&FieldType`) that is cloned into the constructed value, unless it
/// carries `#[constructor_default(EXPR)]` (see below). The return type is always wrapped in
/// `Result<_, puffin::algebra::error::FnError>` so the functions satisfy `DescribableFunction`.
///
/// Unnamed (tuple) fields become positional parameters named `field_<index>`. Nothing is generated
/// for a union.
///
/// # Helper attributes
///
/// * `#[constructor(SIGNATURE, ProtocolTypes)]` — **required**, on the type. Names the signature
///   the generated functions are registered into (via `puffin::define_signature!`) and their
///   protocol-types type.
/// * `#[constructor_default(EXPR)]` — on a field. Excludes the field from the constructor
///   parameters and initialises it from `EXPR` (a literal, call, path, ...) instead.
/// * `#[constructor_list]` — on the type. Marks it a list *element* type: registers `Vec<Self>` as
///   a readable type and emits `impl VecCodecWoSize for Self`, unless its one flag,
///   `#[constructor_list(no_codec_impl)]`, says the type already has one. Off by default because it
///   needs `Self: Codec`, which only genuine list element types satisfy. The list *type* itself is
///   registered from the constructor arguments that take a `Vec<..>`, not from this attribute.
/// * `#[constructor_skip]` — on an enum variant. Generates nothing at all for that variant. For
///   variants whose payload type no other function symbol can produce, or whose value the rest of
///   the crate cannot act on.
/// * `#[constructor_skip_all]` — on an enum. Skips every variant, so only those carrying
///   `#[constructor_no_skip]` are generated; on a struct it drops the single constructor outright.
///   Use it when the wanted variants are the exception rather than the rule, as in a protocol enum
///   listing every IANA-registered value. It composes with `#[constructor_list]`, which is about
///   `Vec<Self>` rather than the variants and still applies.
/// * `#[constructor_no_skip]` — on an enum variant. Keeps that variant under
///   `#[constructor_skip_all]`, and is rejected without it, where it would be a no-op.
/// * `#[constructor_no_try_read]` — on the type. Keeps the type, and the `Vec<Self>` that
///   `#[constructor_list]` would add, out of the signature's readable types. Required for a type
///   with no `Codec` (only `CodecP`), where the registration would not compile; wanted when `read`
///   needs context the bitstring does not carry, or when `encode` and `read` do not round-trip.
#[proc_macro_derive(
    Constructor,
    attributes(
        constructor,
        constructor_default,
        constructor_list,
        constructor_skip,
        constructor_skip_all,
        constructor_no_skip,
        constructor_no_try_read
    )
)]
pub fn constructor_macro(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = syn::parse_macro_input!(input as syn::DeriveInput);
    let options = ConstructorOptions::parse(&input.attrs);

    // A constructor is registered under the `TypeId` of the type it builds, which only a concrete
    // type has: `define_signature!` has nothing to infer a generic `fn_foo`'s parameters from.
    if !input.generics.params.is_empty() {
        return syn::Error::new_spanned(
            &input.generics,
            "Constructor cannot be derived for a generic type: a function symbol is registered \
             under the TypeId of the type it builds, which only a concrete type has. Register the \
             instantiations that take part in the term algebra by hand, with `define_signature!` \
             and `define_readable_types!`.",
        )
        .to_compile_error()
        .into();
    }

    let constructors = map_type_definition(&input.ident, &input.generics, &input, &options);
    // The readable-type registration is about the type, not about which constructors were
    // generated, so it is emitted here rather than in any of the branches of
    // `map_type_definition`: a type whose variants are all skipped is still a type a bitstring
    // can be read back into.
    let readable_types = add_to_readable_types(&input.ident, &options);
    // Same reasoning for the list types, which follow from the constructors' arguments.
    let list_types = add_to_list_types(&input, &options);

    quote! {
        #constructors
        #readable_types
        #list_types
    }
    .into()
}

/// Stores the metadata used to add a function to the signature
struct SigMetadata {
    /// The signature path, e.g. `MY_SIGNATURE` in `#[constructor(MY_SIGNATURE, MyTypes)]`.
    ///
    /// A qualified path is accepted — `#[constructor(crate::tls::TLS_SIGNATURE,
    /// TLSProtocolTypes)]` — so the derive can be used from a module other than the one
    /// declaring the signature. `define_signature!` munches the leading `segment ::` tokens
    /// itself.
    signature: syn::Path,
    /// The protocol-types type, e.g. `MyTypes` in `#[constructor(MY_SIGNATURE, MyTypes)]`.
    protocol_types: syn::Type,
}
impl SigMetadata {
    fn parse(input: &syn::Attribute) -> syn::Result<Self> {
        input.parse_args_with(|stream: syn::parse::ParseStream| {
            let signature = stream.parse::<syn::Path>()?;
            stream.parse::<Token![,]>()?;
            let protocol_types = stream.parse::<syn::Type>()?;
            Ok(Self {
                signature,
                protocol_types,
            })
        })
    }
}

/// Everything the derive reads off the type's helper attributes, in a single value threaded
/// through every generator.
///
/// A new knob is added by giving it a field here and reading it in [`Self::parse`]: no generator
/// signature has to change, and all of them already have access to it.
struct ConstructorOptions {
    /// The signature and protocol-types the generated functions are registered into, from the
    /// mandatory `#[constructor(SIGNATURE, ProtocolTypes)]`.
    sig_metadata: SigMetadata,
    /// How to generate the `Vec<Self>` constructors, from [`LIST_ATTR`].
    list: ListOptions,
    /// Whether [`SKIP_ALL_ATTR`] inverted the polarity of the per-variant skip.
    skip_all: bool,
    /// Whether [`NO_TRY_READ_ATTR`] asked to keep the type out of the readable types.
    no_try_read: bool,
}

/// What [`LIST_ATTR`] asks for.
#[derive(Default)]
struct ListOptions {
    /// Whether the attribute was present at all.
    enabled: bool,
    /// Whether to emit `impl VecCodecWoSize for Self`.
    codec_impl: bool,
}

impl ListOptions {
    fn parse(attrs: &[syn::Attribute]) -> Self {
        let Some(attr) = has_attr(attrs, LIST_ATTR) else {
            return Self::default();
        };

        let mut options = Self {
            enabled: true,
            codec_impl: true,
        };

        // `#[constructor_list]` carries no arguments; the opt-outs are only present in the
        // `#[constructor_list(...)]` form.
        if !matches!(attr.meta, syn::Meta::Path(_)) {
            let flags = attr
                .parse_args_with(
                    syn::punctuated::Punctuated::<syn::Ident, Token![,]>::parse_terminated,
                )
                .expect("expected #[constructor_list(no_codec_impl)]");
            for flag in flags {
                match flag.to_string().as_str() {
                    "no_codec_impl" => options.codec_impl = false,
                    "only" => panic!(
                        "the #[{LIST_ATTR}] flag `only` was replaced by #[{SKIP_ALL_ATTR}]: keep \
                         #[{LIST_ATTR}] for the codec impl and add #[{SKIP_ALL_ATTR}] to drop \
                         the constructors, which additionally lets #[{NO_SKIP_ATTR}] keep a few \
                         variants"
                    ),
                    other => {
                        panic!("unknown #[{LIST_ATTR}] flag `{other}`, expected `no_codec_impl`")
                    }
                }
            }
        }

        options
    }
}

impl ConstructorOptions {
    /// Reads the options off the attributes of the derived type.
    ///
    /// Panics — the only way a derive macro can report an error at this point — when the
    /// mandatory `#[constructor(...)]` attribute is missing or malformed.
    fn parse(attrs: &[syn::Attribute]) -> Self {
        let attribute = has_attr(attrs, CONSTRUCTOR_ATTR)
            .expect("constructor attribute required for deriving Constructor!");

        let sig_metadata = SigMetadata::parse(attribute).expect(
            "failed parsing constructor attribute : expected #[constructor(SIGNATURE, ProtocolTypes)]",
        );

        assert!(
            has_attr(attrs, SKIP_ATTR).is_none(),
            "#[{SKIP_ATTR}] goes on the variant to skip, not on the type. For an enum built by \
             `enum_builder!`, annotate the `EnumVal` entry, or the `EnumUnknown {{ }}` clause for \
             the synthesised `Unknown` variant. To keep only a few variants of a wide enum, use \
             #[{SKIP_ALL_ATTR}] with #[{NO_SKIP_ATTR}] on the ones to keep."
        );

        let skip_all = has_attr(attrs, SKIP_ALL_ATTR).is_some_and(|attr| {
            assert!(
                matches!(attr.meta, syn::Meta::Path(_)),
                "#[{SKIP_ALL_ATTR}] takes no argument; name the variants to keep with \
                 #[{NO_SKIP_ATTR}] on each of them"
            );
            true
        });

        let no_try_read = has_attr(attrs, NO_TRY_READ_ATTR).is_some_and(|attr| {
            assert!(
                matches!(attr.meta, syn::Meta::Path(_)),
                "#[{NO_TRY_READ_ATTR}] takes no argument"
            );
            true
        });

        Self {
            sig_metadata,
            list: ListOptions::parse(attrs),
            skip_all,
            no_try_read,
        }
    }

    /// Whether the variant is excluded from generation.
    ///
    /// By default a variant is generated unless it carries [`SKIP_ATTR`]. Under [`SKIP_ALL_ATTR`]
    /// the polarity is inverted: it is skipped unless it carries [`NO_SKIP_ATTR`]. The combination
    /// that is a no-op in either mode is rejected rather than ignored, so an attribute that reads
    /// as if it changed something always did.
    fn skips(&self, variant: &syn::Variant) -> bool {
        let name = &variant.ident;
        let skip = has_attr(&variant.attrs, SKIP_ATTR).is_some();
        let keep = has_attr(&variant.attrs, NO_SKIP_ATTR).is_some();

        assert!(
            !(skip && keep),
            "variant `{name}` carries both #[{SKIP_ATTR}] and #[{NO_SKIP_ATTR}]"
        );

        if self.skip_all {
            assert!(
                !skip,
                "#[{SKIP_ATTR}] on variant `{name}` is redundant under #[{SKIP_ALL_ATTR}]: every \
                 variant is already skipped unless it carries #[{NO_SKIP_ATTR}]"
            );
            !keep
        } else {
            assert!(
                !keep,
                "#[{NO_SKIP_ATTR}] on variant `{name}` has no effect without #[{SKIP_ALL_ATTR}] \
                 on the type: variants are generated by default"
            );
            skip
        }
    }
}

fn add_to_signature(fn_name: &syn::Ident, options: &ConstructorOptions) -> TokenStream {
    add_to_signature_with_flags(fn_name, options, quote! {})
}

/// Registers the type — and, under [`LIST_ATTR`], `Vec<Self>` — as one of the signature's
/// readable types, so that `try_read_bytes` can read a bitstring back into it.
///
/// Emits nothing when the type carries [`NO_TRY_READ_ATTR`]. Generic types never reach here, the
/// derive rejects them outright.
fn add_to_readable_types(name: &syn::Ident, options: &ConstructorOptions) -> TokenStream {
    if options.no_try_read {
        return quote! {};
    }

    let signature_name = &options.sig_metadata.signature;
    let protocol_types = &options.sig_metadata.protocol_types;
    let list_type = options.list.enabled.then(|| quote! { Vec<#name>, });

    quote! {
        puffin::define_readable_types!(
            #signature_name,
            #protocol_types;
            #name,
            #list_type
        );
    }
}

/// Registers a list type for every constructor argument that is a `Vec<..>`.
///
/// A list is written where a symbol takes one, so the symbols taking one are what define the list
/// types of a signature -- and this is the one place where such an argument type is still a
/// concrete Rust type, which is what `puffin::algebra::list_types::list_type` needs to capture
/// a builder for it. An argument that turns out not to be a buildable list is skipped by
/// `define_list_types!`, so listing every `Vec<..>` argument here is safe.
fn add_to_list_types(input: &syn::DeriveInput, options: &ConstructorOptions) -> TokenStream {
    let mut types: Vec<&syn::Type> = vec![];

    match &input.data {
        // A skipped struct has no constructor, hence no argument taking a list.
        syn::Data::Struct(st) if !options.skip_all => {
            types.extend(vec_arguments(st.fields.iter()));
        }
        syn::Data::Enum(en) => {
            for variant in &en.variants {
                if !options.skips(variant) {
                    types.extend(vec_arguments(variant.fields.iter()));
                }
            }
        }
        _ => {}
    }

    if types.is_empty() {
        return quote! {};
    }

    let signature_name = &options.sig_metadata.signature;
    let protocol_types = &options.sig_metadata.protocol_types;
    quote! {
        puffin::define_list_types!(
            #signature_name,
            #protocol_types;
            #(#types),*
        );
    }
}

/// The constructor-argument types of `fields` that are spelled `Vec<..>`.
///
/// `#[constructor_default(..)]` fields are filled in by the derive rather than passed in, so they
/// are no argument and cannot hold a list the term algebra builds.
fn vec_arguments<'a>(
    fields: impl IntoIterator<Item = &'a syn::Field>,
) -> impl Iterator<Item = &'a syn::Type> {
    fields
        .into_iter()
        .filter(|field| has_attr(&field.attrs, DEFAULT_ATTR).is_none())
        .map(|field| &field.ty)
        .filter(|ty| {
            matches!(ty, syn::Type::Path(path)
                if path.path.segments.last().is_some_and(|s| s.ident == "Vec"))
        })
        .collect::<Vec<_>>()
        .into_iter()
}

/// Same as [`add_to_signature`], with the `define_signature!` flags (`[list]`, ...) appended to
/// the function name.
fn add_to_signature_with_flags(
    fn_name: &syn::Ident,
    options: &ConstructorOptions,
    flags: TokenStream,
) -> TokenStream {
    let signature_name = &options.sig_metadata.signature;
    let protocol_types = &options.sig_metadata.protocol_types;
    quote! {
        puffin::define_signature!(
            #signature_name,
            #protocol_types;
            #fn_name #flags
        );
    }
}

/// Lints to silence on every generated function.
///
/// A term-algebra function symbol must take its arguments exactly as `&FieldType` — `&[T]` is
/// not a registered type, and the parameter count follows the type's field count — so
/// `ptr_arg` and `too_many_arguments` fire on generated code the author cannot restructure.
fn generated_fn_attrs() -> TokenStream {
    quote! {
        #[allow(clippy::ptr_arg, clippy::too_many_arguments)]
    }
}

/// Emits `impl VecCodecWoSize for Self`, so that `Vec<Self>: Codec` -- what makes a list of this
/// type an `EvaluatedTerm` and hence buildable.
///
/// The list type itself is registered by [`add_to_list_types`], from the arguments that take one.
fn register_list_type(
    name: &syn::Ident,
    generics: &syn::Generics,
    options: &ConstructorOptions,
) -> TokenStream {
    let (_, ty_generics, where_clause) = generics.split_for_impl();
    if !options.list.codec_impl {
        return quote! {};
    }

    quote! {
        impl puffin::codec::VecCodecWoSize for #name #ty_generics #where_clause {}
    }
}

fn has_attr<'a>(attrs: &'a [syn::Attribute], attr_name: &str) -> Option<&'a syn::Attribute> {
    attrs.iter().find(|attr| attr.path().is_ident(attr_name))
}

/// Returns the default expression from a `#[constructor_default(EXPR)]` attribute, if present.
///
/// The wrapped tokens are used verbatim as the field's value, so any expression is accepted:
/// a literal (`#[constructor_default(0)]`), a call (`#[constructor_default(my_default())]`), a
/// path (`#[constructor_default(Default::default())]`), etc.
fn default_expr(attrs: &[syn::Attribute]) -> Option<TokenStream> {
    has_attr(attrs, DEFAULT_ATTR).map(|attr| {
        attr.parse_args::<syn::Expr>()
            .expect("expected #[constructor_default(EXPR)] with a single expression")
            .into_token_stream()
    })
}

fn extract_fields<'a>(
    fields: impl IntoIterator<Item = &'a syn::Field>,
    f: impl Fn(usize, Option<syn::Ident>) -> TokenStream,
) -> Vec<TokenStream> {
    let mut result = vec![];

    for (idx, field) in fields.into_iter().enumerate() {
        // Fields with a `#[constructor_default(...)]` are filled in by the macro, so they are
        // not exposed as constructor parameters.
        if has_attr(&field.attrs, DEFAULT_ATTR).is_none() {
            let field_name = f(idx, field.ident.clone());
            let field_type = &field.ty;

            // push field name and type for the function definition
            result.push(quote! {
                #field_name: &#field_type
            });
        }
    }
    result
}

fn field_assignments<'a>(
    fields: impl IntoIterator<Item = &'a syn::Field>,
    f: impl Fn(usize, Option<syn::Ident>) -> TokenStream,
    named: bool,
) -> Vec<TokenStream> {
    let mut result = vec![];

    for (idx, field) in fields.into_iter().enumerate() {
        let field_name = f(idx, field.ident.clone());

        // A `#[constructor_default(EXPR)]` field is initialised from EXPR; every other field is
        // cloned from its (by-reference) constructor parameter.
        let value = match default_expr(&field.attrs) {
            Some(expr) => expr,
            None => quote! { #field_name.clone() },
        };

        if named {
            result.push(quote! {
                #field_name: #value
            });
        } else {
            result.push(quote! {
                #value
            });
        }
    }
    result
}

fn extract_variants<'a>(
    name: &syn::Ident,
    generics: &syn::Generics,
    options: &ConstructorOptions,
    variants: impl IntoIterator<Item = &'a syn::Variant>,
) -> TokenStream {
    let fn_attrs = generated_fn_attrs();
    let mut result = vec![];

    let list_type = if options.list.enabled {
        register_list_type(name, generics, options)
    } else {
        quote! {}
    };

    for variant in variants {
        if options.skips(variant) {
            continue;
        }

        let variant_name = &variant.ident;
        let fn_name = format_ident!(
            "fn_{}_{}",
            name.to_string().to_lowercase(),
            variant_name.to_string().to_lowercase()
        );
        let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
        let add_fn_to_sig = add_to_signature(&fn_name, options);

        match &variant.fields {
            syn::Fields::Named(named) => {
                let field_extractions = extract_fields(named.named.iter(), |_, idt| {
                    let name = idt.expect("unnamed field in named enum");
                    quote! {#name}
                });

                let assignments = field_assignments(named.named.iter(), |_, idt| {
                    let name = idt.expect("unnamed field in named enum");
                    quote! {#name}
                }, true);

                result.push(quote! {
                    #fn_attrs

                    pub fn #fn_name #impl_generics (#(#field_extractions),*) -> Result<#name #ty_generics, puffin::algebra::error::FnError>  #where_clause {
                        Ok(#name::#variant_name {
                            #(#assignments),*
                        })
                    }
                });
            }
            syn::Fields::Unnamed(unnamed) => {
                let field_extractions = extract_fields(unnamed.unnamed.iter(), |idx, _| {
                    let name = format_ident!("field_{}", syn::Index::from(idx));
                    quote! {#name}
                });
                let assignments = field_assignments(unnamed.unnamed.iter(), |idx, _| {
                    let name = format_ident!("field_{}", syn::Index::from(idx));
                    quote! {#name}
                }, false);
                result.push(quote! {
                    #fn_attrs

                    pub fn #fn_name #impl_generics (#(#field_extractions),*) ->  Result<#name #ty_generics, puffin::algebra::error::FnError> #where_clause {
                        Ok(#name::#variant_name (
                            #(#assignments),*
                        ))
                    }
                });
            }
            syn::Fields::Unit => result.push(quote! {
                #fn_attrs

                pub fn #fn_name #impl_generics () ->  Result<#name #ty_generics , puffin::algebra::error::FnError> #where_clause {
                    Ok(#name::#variant_name)
                }
            }),
        }

        result.push(quote! {
            #add_fn_to_sig
        })
    }
    quote! {
        #(#result)*

        #list_type
    }
}

fn map_type_definition(
    name: &syn::Ident,
    generics: &syn::Generics,
    input: &syn::DeriveInput,
    options: &ConstructorOptions,
) -> TokenStream {
    // A struct has no variants to opt back in, so `#[constructor_skip_all]` drops its single
    // constructor outright. The codec impl is about `Vec<Self>` and survives, which is what an
    // element type wanting only that asks for.
    if options.skip_all && !matches!(input.data, syn::Data::Enum(_)) {
        return if options.list.enabled {
            register_list_type(name, generics, options)
        } else {
            quote! {}
        };
    }

    match &input.data {
        syn::Data::Struct(st) => {
            let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
            let fn_attrs = generated_fn_attrs();
            let fn_name = format_ident!("fn_{}", name.to_string().to_lowercase());
            let add_fn_to_sig = add_to_signature(&fn_name, options);
            let register_list_type = if options.list.enabled {
                register_list_type(name, generics, options)
            } else {
                quote! {}
            };

            match &st.fields {
                syn::Fields::Named(named) => {
                    let field_extractions = extract_fields(named.named.iter(), |_, idt| {
                        let name = idt.expect("unnamed field in named struct");
                        quote! {#name}
                    });
                    let assignments = field_assignments(
                        named.named.iter(),
                        |_, idt| {
                            let name = idt.expect("unnamed field in named struct");
                            quote! {#name}
                        },
                        true,
                    );

                    quote! {
                        #fn_attrs

                        pub fn #fn_name #impl_generics (#(#field_extractions),*) ->  Result<#name #ty_generics, puffin::algebra::error::FnError> #where_clause {
                            Ok(#name {
                                #(#assignments),*
                            })
                        }

                        #add_fn_to_sig
                        #register_list_type
                    }
                }
                syn::Fields::Unnamed(unnamed) => {
                    let field_extractions = extract_fields(unnamed.unnamed.iter(), |idx, _| {
                        let name = format_ident!("field_{}", syn::Index::from(idx));
                        quote! {#name}
                    });
                    let assignments = field_assignments(
                        unnamed.unnamed.iter(),
                        |idx, _| {
                            let name = format_ident!("field_{}", syn::Index::from(idx));
                            quote! {#name}
                        },
                        false,
                    );

                    quote! {
                        #fn_attrs

                        pub fn #fn_name #impl_generics (#(#field_extractions),*) ->  Result<#name #ty_generics, puffin::algebra::error::FnError>  #where_clause {
                            Ok(#name (
                                #(#assignments),*
                            ))
                        }

                        #add_fn_to_sig
                        #register_list_type
                    }
                }
                syn::Fields::Unit => {
                    quote! {
                        #fn_attrs

                        pub fn #fn_name #impl_generics () ->  Result<#name #ty_generics, puffin::algebra::error::FnError>  #where_clause{
                            Ok(#name {})
                        }

                        #add_fn_to_sig
                        #register_list_type
                    }
                }
            }
        }
        syn::Data::Enum(en) => {
            extract_variants(&input.ident, generics, options, en.variants.iter())
        }
        syn::Data::Union(_un) => {
            quote! {}
        }
    }
}
