#!/usr/bin/env bash

# JSON generated by tlspuffin-analyzer can have u64 integers, this is not supported by some parsers, this fixes overflows

cat stats.json | ~/jq-linux64 '. as $line
          | try fromjson catch $line
          | (.exec_per_sec |= ([., 2147483647] | min))
          | (.intro.elapsed_cycles |= ([., 2147483647] | min))' > stats-fixed.json
