name: on-pr-merged

on:
  push:
    branches:
      - main

permissions:
  contents: write # needed for gh-pages deployment jobs

# NOTE: we prevent parallel runs of this workflow
#
# We change the concurrency settings so that:
#   - only one workflow can run at any time
#   - scheduling a new run will put the run in a waiting queue
#   - scheduling a new run will evict any run already in the waiting queue
#   - started runs are not cancelled
#
# This should prevent successive merges in a short time window to create
# overlapping or partial deployements.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  validation:
    uses: ./.github/workflows/run-validation.yml
    with:
      profile: full

  prebuild:
    needs: [validation]
    name: Pre-build tlspuffin Binaries
    uses: ./.github/workflows/run-prebuild.yml

  benchmark:
    uses: ./.github/workflows/run-benchmarks.yml

  docs:
    name: Build dev Documentation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: setup
        uses: ./.github/actions/setup

      - name: build website
        shell: bash
        run: just docs

      - name: upload dev documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-dev
          path: target/docs
          if-no-files-found: error

  deploy:
    needs: [validation, docs]
    name: Deploy dev Documentation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: download dev documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-dev
          path: docs-dev

      - name: deploy dev documentation
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          folder: docs-dev
          branch: gh-pages
          clean: true
          force: true
