name: on-pr-merged

on:
  push:
    branches:
      - main

permissions:
  contents: write # needed for deployment jobs

jobs:
  validation:
    uses: ./.github/workflows/run-validation.yml
    with:
      profile: fast

  prebuild:
    needs: [validation]
    name: Pre-build tlspuffin Binaries
    uses: ./.github/workflows/run-prebuild.yml

  benchmark:
    uses: ./.github/workflows/run-benchmarks.yml

  docs:
    uses: ./.github/workflows/build-docs.yml

  deploy-docs:
    needs: [validation, docs]
    name: Deploy dev Documentation
    uses: ./.github/workflows/deploy-docs.yml