name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - trailofbits

jobs:
  run-check:
    uses: ./.github/workflows/run-checks.yml
  run-benchmarks:
    uses: ./.github/workflows/run-benchmarks.yml
  build-deploy-docs:
    uses: ./.github/workflows/build-deploy-docs.yml
    with:
      deploy: ${{ github.ref == 'refs/heads/main' }}
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        name:
          - openssl111
          - openssl111j
          - openssl101f_asan
          - openssl102u
          - libressl
          - wolfssl430
          - wolfssl510
          - wolfssl510-sig
          - wolfssl510-skip
          - wolfssl520
          - wolfssl520_asan
          - wolfssl530
          - wolfssl530_asan
          - wolfssl540
          - wolfssl540-sdos2
          - wolfssl530-cdos
          - wolfssl540_asan
          - wolfssl540-buf
          - wolfssl540-heap
          - wolfssl540_asan-perf
          - wolfssl540-perf
          - libssh
          - tlspuffin_no_default_features
          - sshpuffin_no_default_features
        include:
          - name: openssl111
            crate: tlspuffin
            features: openssl111
            clean-crates: openssl-sys
            save-cache: true # We only save the cache once, else we get too mache cache entries
          - name: openssl111j
            crate: tlspuffin
            features: openssl111j
            clean-crates: openssl-sys
          - name: openssl101f_asan
            crate: tlspuffin
            features: openssl101f,asan
            apt-dependencies: xutils-dev
            clean-crates: openssl-sys
          - name: openssl102u
            crate: tlspuffin
            features: openssl102u
            clean-crates: openssl-sys
          - name: libressl
            crate: tlspuffin
            features: libressl
          - name: wolfssl430
            crate: tlspuffin
            features: wolfssl430
          - name: wolfssl510
            crate: tlspuffin
            features: wolfssl510
          - name: wolfssl510-sig
            crate: tlspuffin
            features: wolfssl510,fix-CVE-2022-25640,fix-CVE-2022-39173
          - name: wolfssl510-skip
            crate: tlspuffin
            features: wolfssl510,fix-CVE-2022-25638,fix-CVE-2022-39173
          - name: wolfssl520
            crate: tlspuffin
            features: wolfssl520
          - name: wolfssl520_asan
            crate: tlspuffin
            features: wolfssl520,asan
          - name: wolfssl530
            crate: tlspuffin
            features: wolfssl530
          - name: wolfssl530_asan
            crate: tlspuffin
            features: wolfssl530,asan
          - name: wolfssl540
            crate: tlspuffin
            features: wolfssl540
          - name: wolfssl540-sdos2
            crate: tlspuffin
            features: wolfssl540,wolfssl-disable-postauth,fix-CVE-2022-39173
          - name: wolfssl530-cdos
            crate: tlspuffin
            features: wolfssl530,fix-CVE-2022-39173
          - name: wolfssl540_asan
            crate: tlspuffin
            features: wolfssl540,asan
          - name: wolfssl540-buf
            crate: tlspuffin
            features: wolfssl540,fix-CVE-2022-42905
          - name: wolfssl540-heap
            crate: tlspuffin
            features: wolfssl540,asan,fix-CVE-2022-39173
          - name: wolfssl540_asan-perf
            crate: tlspuffin
            features: wolfssl540,asan,fix-CVE-2022-39173,fix-CVE-2022-42905
          - name: wolfssl540-perf
            crate: tlspuffin
            features: wolfssl540,fix-CVE-2022-39173,fix-CVE-2022-42905
          - name: libssh
            crate: sshpuffin
            features: ""
          - name: tlspuffin_no_default_features
            crate: tlspuffin
            features: ""
            cargo-flags: "--no-default-features"
          - name: sshpuffin_no_default_features
            crate: sshpuffin
            features: ""
            cargo-flags: "--no-default-features"
    uses: ./.github/workflows/build-linux.yml
    with:
      name: ${{ matrix.name }}
      crate: ${{ matrix.crate }}
      features: ${{ matrix.features }}
      cargo-flags: ${{ matrix.cargo-flags }}
      apt-dependencies: ${{ matrix.apt-dependencies }}
      clean-crates: ${{ matrix.clean-crates }}
      save-cache: ${{ matrix.save-crates }}
